Name : Sadikur Rahman Khaled
ID : 160103020044
Section : B

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris =  datasets.load_iris() 
x = iris.data
y = iris.target

In [3]:
print(x[:5])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
def u_dis(x, y):
    ud={}
    for i in range(len(x)):
        d=np.linalg.norm(x[i]-y)
        ud[i]=d
    return ud

In [5]:
#xt=[5.1, 3., 4.2, 1.5]
# xt=[6.7, 3.3, 5.7, 2.1]
xt=[]
print("Enter The Value Of TX")
for i in range(len(x[0])):
    t=eval(input())
    xt.append(t)
ud=u_dis(x,xt)

Enter The Value Of TX
4
2
1
2


In [6]:
print(ud)

{0: 2.619160170741759, 1: 2.282542442102666, 2: 2.293468988235943, 3: 2.2494443758403984, 4: 2.638181191654584, 5: 2.93598365118064, 6: 2.3173260452512934, 7: 2.539685019840059, 8: 2.090454496036687, 9: 2.4248711305964283, 10: 2.8879058156387307, 11: 2.4899799195977463, 12: 2.325940669922601, 13: 2.17025344142107, 14: 3.243454948045371, 15: 3.385262175962152, 16: 2.86705423736629, 17: 2.5514701644346145, 18: 3.083828789021855, 19: 2.754995462791182, 20: 2.7658633371878665, 21: 2.6286878856189833, 22: 2.4819347291981715, 23: 2.3748684174075834, 24: 2.578759391645525, 25: 2.3664319132398464, 26: 2.4248711305964283, 27: 2.6795522013948525, 28: 2.6076809620810595, 29: 2.3515952032609695, 30: 2.3345235059857505, 31: 2.5942243542145698, 32: 3.116087290176576, 33: 3.23882694814033, 34: 2.3473389188611007, 35: 2.3916521486202797, 36: 2.7982137159266447, 37: 2.6720778431774774, 38: 2.118962010041709, 39: 2.580697580112788, 40: 2.495996794869737, 41: 1.8220867158288596, 42: 2.220360331117452, 43

In [7]:
s_ud = sorted(ud.items(), key=lambda kv: kv[1])

In [8]:
print(s_ud)

[(41, 1.8220867158288596), (8, 2.090454496036687), (38, 2.118962010041709), (45, 2.1656407827707715), (13, 2.17025344142107), (42, 2.220360331117452), (3, 2.2494443758403984), (47, 2.280350850198276), (1, 2.282542442102666), (2, 2.293468988235943), (6, 2.3173260452512934), (12, 2.325940669922601), (30, 2.3345235059857505), (34, 2.3473389188611007), (29, 2.3515952032609695), (43, 2.360084744241189), (25, 2.3664319132398464), (23, 2.3748684174075834), (35, 2.3916521486202797), (9, 2.4248711305964283), (26, 2.4248711305964283), (49, 2.467792535850613), (22, 2.4819347291981715), (11, 2.4899799195977463), (40, 2.495996794869737), (98, 2.5039968051097827), (7, 2.539685019840059), (17, 2.5514701644346145), (24, 2.578759391645525), (39, 2.580697580112788), (31, 2.5942243542145698), (28, 2.6076809620810595), (0, 2.619160170741759), (21, 2.6286878856189833), (4, 2.638181191654584), (37, 2.6720778431774774), (27, 2.6795522013948525), (57, 2.694438717061496), (93, 2.7166155414412247), (19, 2.75499

In [9]:
#k=9
print("Enter The Value Of K :")
k=eval(input())
sk=[]
for i in range(k):
    sk.append(s_ud[i][0])
print(sk)

Enter The Value Of K :
5
[41, 8, 38, 45, 13]


In [10]:
ry=[]
for i in range(k):
    ry.append(y[sk[i]])
print(ry)

[0, 0, 0, 0, 0]


In [11]:
ue,c_ue=np.unique(ry,return_counts=True)
print(ue)
print(c_ue)

[0]
[5]


In [12]:
max_ind=c_ue.argmax(axis=0)
py=ue[max_ind]
print(py)

0


In [13]:
x1=[4,2,1,2]
x2=[1,2,3,4]
s=0
for i in range(len(x1)):
    s+=(x1[i]-x2[i])**2
s2=np.sqrt(s)
print(s2)

4.123105625617661
